version: "3.8"

services:
  web:
    build: .
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BASE_PATH=/untp-playground
